### ISSUE TITLE
Invalid cache hit when reading files created with writeStream

### ISSUE THREAD

**Issue by zaak** [thephpleague/flysystem-cached-adapter#18]
Consider a following code sample:

``` php
use League\Flysystem\Adapter\Local;
use League\Flysystem\Cached\CachedAdapter;
use League\Flysystem\Filesystem;
use League\Flysystem\Cached\Storage\Memory;

$memoryCache = new Memory();
$adapter = new CachedAdapter(new Local('/tmp'), $memoryCache);
$filesystem = new Filesystem($adapter);

// Some dummy stream
$stream = fopen('data://text/plain,TEST', 'r');

$filesystem->writeStream('foo.txt', $stream);

var_dump($filesystem->read('foo.txt')); // bool(false)
```

It's because stream `contents` are saved as `false` [here](https://github.com/thephpleague/flysystem-cached-adapter/blob/master/src/CachedAdapter.php#L75).
The cache hit occurs, because `read()` [here](https://github.com/thephpleague/flysystem-cached-adapter/blob/master/src/Storage/AbstractCache.php#L163) checks only if the key exists using `isset()`. I believe it should be checked also if `contents` at this point is not `false`.

**Comment by jak** [comment]
workaround is to read content of the stream:
```
$stream = fopen('data://text/plain,TEST', 'r');

// $filesystem->writeStream('foo.txt', $stream);
rewind($stream);
$contents = stream_get_contents($stream);
$filesystem->write('foo.txt', $contents);
```
