### ISSUE TITLE
Support for PhpRedis?

### ISSUE THREAD

**Issue by yellow1912** [thephpleague/flysystem-cached-adapter#2]
PHPRedis is the C extension for PHP to work with Redis which should give much better performance compared to Predis. 

The code is rather simple, I can take the responsibility of writing it and send PR if necessary?

**Comment by frankdejonge** [comment]
@yellow1912 a PR would be very welcome!

**Comment by GrahamCampbell** [comment]
@yellow1912 I have a cache adapter that bridges to the illuminate cache component, which supports redis as part of my laravel bridge if you need something quick.

**Comment by yellow1912** [comment]
@GrahamCampbell actually I already have it working I think. But looks like we are already supporting Stash which in turns also supports PhpRedis so I'm thinking it's not necessary to add support to PhpRedis directly?

**Comment by GrahamCampbell** [comment]
Better close this then. :)
