### ISSUE TITLE
Why dont you cache empty directories

### ISSUE THREAD

**Issue by adyballa** [thephpleague/flysystem-cached-adapter#28]
As I investigate the performance on our site, I spotted that a directories call on an empty directory lasts half a second. It will not be cached if it is empty. Is it necessary to do it?

https://github.com/thephpleague/flysystem-cached-adapter/blob/master/src/CachedAdapter.php#L251 

regards

**Comment by frankdejonge** [comment]
Fixed in 93eec679c

**Comment by frankdejonge** [comment]
Just tagged 1.0.6 for this.
