### ISSUE TITLE
Bug when using with elFinder

### ISSUE THREAD

**Issue by liverbool** [thephpleague/flysystem-cached-adapter#29]
###  Bug on

`\League\Flysystem\Cached\Storage\AbstractCache::listContents`
or maybe
`\League\Flysystem\Cached\Storage\AbstractCache::storeContents`

<img width="1042" alt="2560-09-24 19 13 53" src="https://user-images.githubusercontent.com/206804/30782448-c9b007ce-a15c-11e7-99bf-f1a53308bc80.png">

The path should be: `/Users/dos/www/phpmob/changmin/app/../var/media/private/admins`

### Trace log

Scandir:
```
/private
    /admins
        /6e3e6bde57bd81751c3bc7d6cdafc313.jpeg
````

Non-cached result:
```
CachedAdapter.php on line 249:
array:1 [
  0 => array:3 [
    "type" => "dir"
    "path" => "private"
    "timestamp" => 1506231712
  ]
]

CachedAdapter.php on line 249:
array:1 [
  0 => array:4 [
    "type" => "file"
    "path" => "private/admins/6e3e6bde57bd81751c3bc7d6cdafc313.jpeg"
    "timestamp" => 1506231712
    "size" => 14977
  ]
]

CachedAdapter.php on line 249:
array:1 [
  0 => array:3 [
    "type" => "dir"
    "path" => "private/admins"
    "timestamp" => 1506231712
  ]
]

CachedAdapter.php on line 249:
array:1 [
  0 => array:3 [
    "type" => "dir"
    "path" => "private"
    "timestamp" => 1506231712
  ]
]
```
 
Cached result:
```
CachedAdapter.php on line 246:
array:2 [
  0 => array:5 [
    "dirname" => ""
    "basename" => "admins"
    "filename" => "admins"
    "path" => "admins"
    "type" => "dir"
  ]
  1 => array:6 [
    "dirname" => ""
    "basename" => "private"
    "filename" => "private"
    "path" => "private"
    "type" => "dir"
    "timestamp" => 1506231712
  ]
]

CachedAdapter.php on line 246:
array:1 [
  0 => array:9 [
    "dirname" => "private/admins"
    "basename" => "6e3e6bde57bd81751c3bc7d6cdafc313.jpeg"
    "extension" => "jpeg"
    "filename" => "6e3e6bde57bd81751c3bc7d6cdafc313"
    "path" => "private/admins/6e3e6bde57bd81751c3bc7d6cdafc313.jpeg"
    "type" => "file"
    "size" => 14977
    "timestamp" => 1506231712
    "mimetype" => "image/jpeg"
  ]
]

CachedAdapter.php on line 246:
array:1 [
  0 => array:6 [
    "dirname" => "private"
    "basename" => "admins"
    "filename" => "admins"
    "path" => "private/admins"
    "type" => "dir"
    "timestamp" => 1506231712
  ]
]

CachedAdapter.php on line 246:
array:2 [
  0 => array:5 [
    "dirname" => ""
    "basename" => "admins"
    "filename" => "admins"
    "path" => "admins"
    "type" => "dir"
  ]
  1 => array:6 [
    "dirname" => ""
    "basename" => "private"
    "filename" => "private"
    "path" => "private"
    "type" => "dir"
    "timestamp" => 1506231712
  ]
]
```

ping @frankdejonge

**Comment by frankdejonge** [comment]
This is not related to cache. Flysystem uses SplFileInfo::getType to check if we're dealing with files, directories or links. We need this functionality. Where you use Flysystem you should have the correct permissions to do so. PHP itself throws the Fatal exception here, so it's more a PHP issue than a Flysystem issue to begin with.

**Comment by liverbool** [comment]
Seem the path is wrong 
`/Users/dos/www/phpmob/changmin/app/../var/media/admins`
it should be:
`/Users/dos/www/phpmob/changmin/app/../var/media/private/admins`

**Comment by frankdejonge** [comment]
Can you send me some code to reproduce this? An isolated scenario, not one with elfinder.

**Comment by liverbool** [comment]
https://github.com/1up-lab/OneupFlysystemBundle
Here is flysystem config: https://github.com/phpmob/changmin/blob/03b0ab28ee622d7449ae8b03428b9da2aaa7104c/src/PhpMob/MediaBundle/Resources/config/app/main.yml

https://github.com/helios-ag/FMElfinderBundle
And here is elfinder: https://github.com/phpmob/changmin/blob/03b0ab28ee622d7449ae8b03428b9da2aaa7104c/src/PhpMob/MediaBundle/Resources/config/app/fm_elfinder.yml#L25

**Comment by frankdejonge** [comment]
Yeah, I'm not going to set that all up just to verify if this is even an issue with Flysystem or something else in the chain. All I see now is that lstat failed, which is causing the error.
