### ISSUE TITLE
Please consider exposing client and cache

### ISSUE THREAD

**Issue by yellow1912** [thephpleague/flysystem-cached-adapter#3]
When using the Flysystem plugin pattern, it's necessary to get access to client to run public methods available for specific client (such as getObjectUrl for s3 client).

Exposing cache allows the plugin to utilize caching when necessary.

**Comment by Twiebie** [comment]
This would be awesome!

**Comment by frankdejonge** [comment]
A PR has just been merged which ads the `getAdapter` method.

**Comment by bbatsche** [comment]
What about the cache implementation? I would be nice if I could easily `flush()` the cache from my controller.

**Comment by barryvdh** [comment]
Pr submitted in #17
