### ISSUE TITLE
Missing array check in Adapter class

### ISSUE THREAD

**Issue by hcomnetworkers** [thephpleague/flysystem-cached-adapter#39]
Hello,

we received the following error:

`"array_key_exists() expects parameter 2 to be array, null given"`

The issue appears on line 300 of `League\Flysystem\Cached\Storage\AbstractCache.php`, where the variable `$complete` is expected to be an array, but actually is null.

On further inspection we found out that the issue comes from the `setFromStorage` method. 
The original method in `League\Flysystem\Cached\Storage\AbstractCache.php` on line 380 has a check, if `$complete` is an array. This function is overwritten by `League\Flysystem\Cached\Storage\Adapter.php` on line 66 and does not have this `is_array` check, which can lead to the mentioned error. 

It would be great if you could adjust the implementation, so that the extending class uses the same checks as the base class.

**Comment by frankdejonge** [comment]
Hi, @hcomnetworkers if you could send a PR, that'd be 👍

**Comment by hcomnetworkers** [comment]
@frankdejonge we have sent you a pull request ✔️

**Comment by hcomnetworkers** [comment]
Hello @frankdejonge , 
when can we expect to merge this pull request? ✔️ #40 

Only small changes have been made and all tests are successful. The changes should not have a major impact on the rest of the program.

With kind regards
h.com Networkers Team

**Comment by frankdejonge** [comment]
It's released as 1.1.0

**Comment by hcomnetworkers** [comment]
Thanks a lot for the merge! 🎉 

With kind regards
h.com Networkers Team
