### ISSUE TITLE
Bug with the Adapter Storage

### ISSUE THREAD

**Issue by yellow1912** [thephpleague/flysystem-cached-adapter#4]
The particular method below from the Adapter Storage assigns the $cache and $complete directly without checking. Since we expect these 2 parameters to be array type in many methods in our AbstractCache class we will run into unexpected errors here.

```php
public function setFromStorage($json)
    {
        list($cache, $complete, $expire) = json_decode($json, true);

        if (! $expire || $expire > $this->getTime()) {
            $this->cache = $cache;
            $this->complete = $complete;
        } else {
            $this->adapter->delete($this->file);
        }
    }
```

**Comment by frankdejonge** [comment]
@yellow1912 could you elaborate on this? Are there cases where these are not arrays?

**Comment by yellow1912** [comment]
I believe I was use the local cache adapter and the specified cache file was not available causing the results returned to be null.

**Comment by frankdejonge** [comment]
@yellow1912 this is fixed now, thanks to @shadowhand.
