### ISSUE TITLE
Deleting a file does not remove from cache

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/flysystem-cached-adapter#7]
After calling `$filesystem->delete($file)` calling `$filesystem->has($file)` should return false. Cache for the file should be cleared when the file is deleted.

**Comment by shadowhand** [comment]
Actually it seems that CachedAdapter attempts to do the right thing, but it looks like AWSv2 is failing to return a `DeleteMarker` [here](https://github.com/thephpleague/flysystem-aws-s3-v2/blob/3c987f0b9fc6e9c55f2d3341b82cf016d7098760/src/AwsS3Adapter.php#L293) which then causes the file to not be purged from cache.

**Comment by shadowhand** [comment]
The error message I receive is:

> Aws\S3\Exception\NoSuchKeyException thrown with message "The specified key does not exist."

**Comment by frankdejonge** [comment]
@shadowhand could you re-check this? I've tried to reproduce this by doing: 

```php
var_dump($filesystem->has('something.txt'));
var_dump($filesystem->write('something.txt', 'text input'));
var_dump($filesystem->has('something.txt'));
var_dump($filesystem->delete('something.txt'));
var_dump($filesystem->has('something.txt'));
```

Though, no exceptions are thrown.

**Comment by frankdejonge** [comment]
@shadowhand is this still accurate?

**Comment by shadowhand** [comment]
I'm not able to reproduce it. Might have been a misconfiguration on our part, or perhaps a bug in AWS SDK that has been fixed.
